<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-18 19:03
=======
# Generated by Django 4.0.3 on 2022-03-18 18:18
>>>>>>> 67cbade0de7f8db68e4643d5482512ae93667c74

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ('comment', '0001_initial'),
=======
>>>>>>> 67cbade0de7f8db68e4643d5482512ae93667c74
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
<<<<<<< HEAD
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
=======
>>>>>>> 67cbade0de7f8db68e4643d5482512ae93667c74
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
